name: Update README with Tasks

on:
  push:
    branches:
      - main
    paths:
      - '01-FEITO.md'
      - '02-FAZENDO.md'
      - '03-FAZER.md'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run update script
        run: python .github/scripts/update_readme.py

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update README with task status"
            git push
          fi
